[project]
channels = ["conda-forge"]
name = "ATMLO"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">3.9,<3.11"
pytorch-gpu = "*"
matplotlib = "*"
seaborn = ">=0.13.2,<0.14"
fsspec = "<=2024"
openai = ">=1.66.3,<2"

[system-requirements]
cuda = "11.8"

[pypi-dependencies]
auto-circuit = ">=1.0.1, <2"
pyvene = ">=0.1.0"
vec2text = ">=0.0.13, <0.0.14"
